#!/usr/bin/env python3


"""
Shutdown pc plz by Toka (Sleep)
"""

import os
import PySimpleGUI as sg

sg.theme('DarkAmber')
layout = [
    [sg.Text('Shutdown:', size=(10, 1)), sg.Button('Shutdown', size=(15, 1))
     ],
    [sg.Text('Abort:', size=(10, 1)), sg.Button('Abort', size=(15, 1))
     ],
    [sg.Text('Tokadown v0.1, by Toka', size=(20, 1), key=('output'))
     ],
    [sg.Button('Exit', size=(10, 1)), sg.Button('Settings', size=(10, 1))]]

window = sg.Window('Tokadown v0.1', layout)
while True:
    event, values = window.read()
    if event in (None, 'Exit'):
        exit(0)
    elif event in ('Shutdown in 5 minutes'):
        os.system('shutdown /t 300 /s')
        window.FindElement('output').Update("Shutting down in 5 minutes")
    elif event in ('Abort shutdown'):
        os.system('shutdown /a')
        window.FindElement('output').Update("Shutdown cancelled")


window.close()
